### ISSUE TITLE
Настройка линтера

### ISSUE THREAD

**Issue by walleri1** [walleri1/sbermortgagecalculator#4]
Настроить линтер по предоставленному файлу `golangci-lint`:
```yaml
run:
  concurrency: 4
  timeout: 1m
  tests: false
  issues-exit-code: 0
  go: '1.21'

output:
  format: colored-line-number

issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000
  exclude-use-default: false

linters-settings:
  prealloc:
    for-loops: true

  stylecheck:
    go: "1.21"
    checks: ["all"]

  staticcheck:
    go: "1.21"
    checks: ["all"]

  nolintlint:
    allow-unused: true
    require-explanation: true
    require-specific: true

  gosimple:
    go: "1.21"
    checks: ["all"]

  gocyclo:
    min-complexity: 20

  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

  dupl:
    threshold: 70

  dogsled:
    max-blank-identifiers: 2

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true
    shadow:
      strict: true

  funlen:
    lines: 60
    statements: 60
    ignore-comments: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomodguard
    - revive
    - gosec
    - gosimple
    - govet
    - godot
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  presets:
    - comment
    - error
```
